<table class="datatable">
    <thead>
     <tr>
      <th>Region</th>
      <th>Power</th>
      <th>Calories</th>
      <th>My rank</th>
     </tr>
    </thead>
    <tbody>
      <tr>
      <td>West</td>
      <td>1435</td>
      <td>1801</td>
      <td>1</td>
     </tr>
     <tr>
      <td>USA</td>
      <td>2435</td>
      <td>2801</td>
      <td>18</td>
     </tr>
     <tr>
     <td>Global</td>
      <td>4435</td>
      <td>4801</td>
      <td>234</td>
     </tr>
    </tbody>
   </table>