
<div id="main" role="main">
<!-- Call to action ================= -->
            <section class="call-to-action">
                <div class="container">
                    <div class="row-fluid">

                        <div class="widget call-to-action">
                            <div class="span9">
                                <p>New FitForGreen's Application for smartphones</p>
                            </div>
                            <div class="span3">
                                <a href="/prereg" class="btn btn-cta">Get it now &raquo;</a>
                            </div>
                        </div><!-- /call-to-action -->

                    </div>
                </div><!-- /container -->
            </section><!-- /call-to-action -->



            <!-- Content area ================== -->
            <section class="content">

                <div class="container">
                    
                    <div class="row-fluid">
                        <div class="span12">
                            <h2 style="text-align:center; margin-bottom:15px;">What is Fit for Green All About?</h2>
                            <p>Fit for Green offers a line of software products that help ordinary people track and improve their fitness levels.  These products include a mobile application, web application, and an in-gym fitness application.  Regardless of the exercise, Fit for Green tracks it in terms of power generated by the user.  For example; that person just did a 600 watt spin class.  By measuring power we’re able to put everything in terms of real work completed.  Power is easier to understand because we can relate it to everyday things like how much energy your house consumes or how much energy it takes to keep a light on.  Besides the fact that power is a pure unit of work, it is also a good metric to gamify.  For example, we have east coast people trying to power the Empire State building before west coast people power the Golden Gate Bridge or we put democrats against republicans to see who can make enough power to light the Whitehouse first.  For these games your power generated become points that can be applied towards the contests which provide additional incentives and make it fun for people to be more active.  Depending on the contest there may even be rewards for top contributors.</p>
							<p>Fit for Green is unlike other fitness applications because it focuses exclusively on raising your personal power levels and it focuses on the casual exerciser.  Power can be measured in a number of ways but the most common is by heart rate.  If we know a person’s height, weight, gender, and age plus we can measure or estimate their heart rate we can then tell how much work they did.  This work can be expressed as watt-hours and/or calories.  Unlike other fitness applications Fit for Green does not focus on the avid biker, runner, or weight lifter.  For the measurement of power we also bring the first BYOD (Bring Your Own Device) fitness applications.  Where others focus on a device for a specific sport measurement or use GPS to track progress, Fit for Green will calculate power created from any device.  At first we’ll focus on leading brand like the Fitbit and the Polar Heart Monitor but one of our core competencies will be in maintaining multiple device interfaces. </p>
                            
                        </div>
                    
                    </div>
                    
                    <div class="row-fluid">
                        <div class="span12">

<h2 style="text-align:center;">Check Our Videos</h2>
<ul class="portfolio-3col row-fluid" >       
    <li class="span4">
        <div class="portfolio-blockimg2">
            <div class="portfolio-imgbox2">
                <div class="play">
                    <a href="http://www.youtube.com/watch?v=6R8nAAKUzuc" rel="prettyPhoto" title="Introduction to Fit for Green"><img src="/css/promo/images/video1.png" class="boximg-pad2 fade" /></a>
                </div>

            </div>
            <h4><a href="#">Introduction to Fit for Green</a></h4>
            <p>This brief introductory presentation will feature an explanation of the Fit for Green solution, and give a current status of the company and product.</p>       
        </div>
    </li>

    <li class="span4">
        <div class="portfolio-blockimg2">
            <div class="portfolio-imgbox2">
                <div class="play">
                    <a href="http://www.youtube.com/watch?v=rWEGM3eeRVE" rel="prettyPhoto" title="Loggin in and Registering"><img src="/css/promo/images/video2.png" class="boximg-pad2 fade" /></a>
                </div>
            </div>
            <h4><a href="#">Logging in and Registering</a></h4>
            <p>This a brief demonstration that explains how users register and log in to become a Fit for Green member. Both in-gym and in-home processes are shown.</p>            
        </div>
    </li>

    <li class="last span4">
        <div class="portfolio-blockimg2">

            <div class="portfolio-imgbox2">
                <div class="play">
                    <a href="http://www.youtube.com/watch?v=ikWy1xN0rUk" rel="prettyPhoto" title="The Workout Experience"><img src="/css/promo/images/video3.png" class="boximg-pad2 fade" /></a>
                </div>
            </div>
            <h4><a href="#">The Workout Experience</a></h4>
            <p>This brief demonstration will show what users experience when they work out in a gym that owns the Fit for Green solution.</p>
        </div>
    </li>     

</ul>
                            
                        </div>
                    </div>

                </div><!-- /container -->

            </section><!-- /content -->
        </div><!-- /main -->
